ALTER TABLE event
    ADD COLUMN is_disabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE event_seat_category
    ADD COLUMN is_disabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE event_show
    ADD COLUMN is_disabled BOOLEAN NOT NULL DEFAULT FALSE;